### Quiz

In [2]:
import numpy as np

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [3]:
# A1.
a = np.array(['강아지', '원숭이', '꽃', '45', '100'])
a, a.ndim, a.size, type(a), a.shape

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3'),
 1,
 5,
 numpy.ndarray,
 (5,))

In [4]:
# A2.
a = np.array(['강아지', '원숭이', '꽃', '45', '100'])
a, a.ndim, a.size, a.dtype, a.shape

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3'),
 1,
 5,
 dtype('<U3'),
 (5,))

In [7]:
# 정답
a= np.array(['강아지','원숭이', '꽃', 45,100])
a, a.ndim, a.size, a.dtype, a.shape

(array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U11'),
 1,
 5,
 dtype('<U11'),
 (5,))

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
b=np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [16]:
# A1. 
c = np.arange(0,81)[51:]
c

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [17]:
c.reshape(6,5)

array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

In [18]:
# A2. 
np.arange(51,81).reshape(6,5)


array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [19]:
d=np.arange(51,81,dtype=float).reshape(6,5)
d, d.dtype

(array([[51., 52., 53., 54., 55.],
        [56., 57., 58., 59., 60.],
        [61., 62., 63., 64., 65.],
        [66., 67., 68., 69., 70.],
        [71., 72., 73., 74., 75.],
        [76., 77., 78., 79., 80.]]),
 dtype('float64'))

In [24]:
#정답
c=c.astype(float)
c, c.dtype

(array([51., 52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63.,
        64., 65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76.,
        77., 78., 79., 80.]),
 dtype('float64'))

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [10]:
# A1.
e = np.array([[ 1,  4,  5,  6],
               [56, 23, 45, 67],
               [ 8,  4,  6, 10]])
e.flatten()[5:-1]

array([23, 45, 67,  8,  4,  6])

In [25]:
# 정답
arr2d= np.array([[ 1,  4,  5,  6],
                 [56, 23, 45, 67],
                 [ 8,  4,  6, 10]])
print(arr2d.flatten()[5:11])

[23 45 67  8  4  6]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [11]:
# A1.
f = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

f[0] = 10
f[[7,8,9]] =0
f

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

In [12]:
# A2.
f = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

f[0] = 10
f[-3:] = 0
f

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [27]:
g = np.random.randint(10,100, (5,5))
print(g)

[[62 33 70 90 33]
 [51 17 27 48 22]
 [31 62 25 90 98]
 [99 13 80 16 24]
 [61 28 82 57 58]]


In [29]:
# 정답
np.random.randint(10,100,25).reshape(5,5)

array([[91, 97, 63, 85, 25],
       [34, 43, 84, 35, 25],
       [54, 21, 40, 52, 21],
       [28, 61, 47, 78, 84],
       [61, 51, 75, 54, 88]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [14]:
# A1.
h = np.arange(1,101)
h

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
h = np.random.randint(1,101,7)
h

array([20, 25, 47,  8, 70, 86, 62])

In [16]:
print("max =", h.max(), "min =", h.min())

max = 86 min = 8


In [17]:
# A2.
h = np.random.randint(1,101,7)
print("max =", np.max(h), "min =", np.min(h))

max = 98 min = 19


In [30]:
# 정답
z=np.random.randint(1,101, 7)
z, np.max(z), np.min(z)

(array([37, 65, 37, 99,  8, 98, 22]), 99, 8)

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [33]:
i = np.arange(1,10).reshape(3,3)
j = np.arange(11,20).reshape(3,3)
k = np.arange(21,30).reshape(3,3)
print(i)
print(j)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [34]:
#Result1
l = np.concatenate((i,j,k), axis=1)
l

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
       [ 7,  8,  9, 17, 18, 19, 27, 28, 29]])

In [35]:
#Result2
m = np.concatenate((i,j,k), axis=0)
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [40]:
# 정답
result2=np.hstack((i, j,k))
result1=np.vstack((i, j,k))
result1, result2

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]),
 array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
        [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
        [ 7,  8,  9, 17, 18, 19, 27, 28, 29]]))

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [41]:
# 중복없이, 100까지 숫자중 40개를 추출가능, randint는 중복생김
arr = np.random.choice(100, 40, replace=False)
# 50보다 큰 숫자만 필터링
# arr[np.where(arr > 50)]
arr[arr > 50]

array([97, 51, 82, 96, 85, 79, 68, 56, 78, 76, 66, 83, 70, 52, 75])

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [46]:
kor = np.array( [60,55,70,30,20,90])
kor

array([60, 55, 70, 30, 20, 90])

In [47]:
# 1. 국어점수가 가장큰값을 구하여라
max(kor)

90

In [48]:
# 2. 국어점수가 80점이상인 값을 구하여라
kor[kor>80]

array([90])

In [49]:
# 3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
kor[(kor >= 50) & (kor <=80)]

array([60, 55, 70])

In [50]:
# 4. 국어점수의 평균을 구하여라
kor.mean()

54.166666666666664

In [51]:
# 5. 국어점수의 총합을 구하여라.
kor.sum()

325

In [52]:
# 6. 국어점수가 40점이하인 데이터를 삭제하여라 (wrong)
# Q. 40점이하의 인덱스?bool : (kor<=40)
# Q. del(배열,인덱스,axis) ???
kor

array([60, 55, 70, 30, 20, 90])

In [53]:
kor <= 40

array([False, False, False,  True,  True, False])

In [54]:
np.argsort(kor)

array([4, 3, 1, 0, 2, 5], dtype=int64)

In [55]:
kor1=np.sort(kor)
kor1

array([20, 30, 55, 60, 70, 90])

In [56]:
np.argsort(kor1)

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [57]:
kor2=kor1[2:]
kor2

array([55, 60, 70, 90])

In [60]:
# 정답
import copy
kora = kor.copy()
num = kor[kor<=40]
kora, num, np.delete(kora,np.where(kor<=40))

(array([60, 55, 70, 30, 20, 90]), array([30, 20]), array([60, 55, 70, 90]))

In [69]:
# 7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라 (wrong)
np.where(kor>=50, kor*1.1, kor)

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [79]:
# 8. 국어점수 top 3를 구하여라 (wrong)
np.sort(kor)[::-1]

array([90, 70, 60, 55, 30, 20])

In [80]:
np.sort(kor)[::-1][:3]

array([90, 70, 60])

In [82]:
np.argsort(kor)[::-1][:3]

array([5, 2, 0], dtype=int64)

In [83]:
kor[np.argsort(kor)[::-1][:3]]

array([90, 70, 60])

In [95]:
# 9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요(wrong)
# 60 '불합격'
# 55 '불합격'
# 입력값으로는 못하나요? 이렇게 프린트하려면?
np.where(kor>=70, '합격', '불합격')

array(['불합격', '불합격', '합격', '불합격', '불합격', '합격'], dtype='<U3')